---
# defaults file for endevel-django
project_name:
django_project_name: main
git_repo:
git_branch:
db_name:
db_pass:
db_user:
settings_file:
project_domain:
project_other_domains: false
project_secret_key:
sentry_dsn:
settings_path: "{{ django_project_name }}.settings.{{ settings_file }}"
eshop: false
python_path: {% if eshop %}"{{ python_install_root }}/bin/{{ python_version }}"{% else %}python3.5{% endif %}

email_host: localhost
email_port: 25
email_password:
email_user:
email_use_tls: false
email_default_from: "info@{{ project_domain }}"

db_superuser: db_superuser
lc_collate: cs_CZ.UTF-8
lc_ctype: cs_CZ.UTF-8
encoding: UTF.8